### ISSUE TITLE
[CRASH] Glutenfree LTN announcer

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Quezler/glutenfree#1]
### Modpack Version

Glutenfree LTN announcer

### Describe your issue.

1270.516 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "Мод LTN - Логистическая сеть поездов (1.16.10) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event LogisticTrainNetwork::on_train_changed_state (ID 25)
Мод Glutenfree LTN announcer (1.0.3) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event glutenfree-ltn-announcer::on_train_schedule_changed (ID 113)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__glutenfree-ltn-announcer__/scripts/speaker.lua:124: in function 'announce'
	__glutenfree-ltn-announcer__/scripts/speaker.lua:116: in function <__glutenfree-ltn-announcer__/scripts/speaker.lua:105>
stack traceback:
	[C]: in function '__newindex'
	__LogisticTrainNetwork__/script/train-events.lua:114: in function 'TrainArrives'
	__LogisticTrainNetwork__/script/train-events.lua:335: in function <__LogisticTrainNetwork__/script/train-events.lua:331>"
1270.516 Info ServerMultiplayerManager.cpp:797: updateTick(87725116) changing state from(InGame) to(Failed)
1270.516 Info SteamContext.cpp:486: Leaving lobby...

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Quezler** [comment]
please use the latest version of this mod (1.0.6 at the time of writing)
