### ISSUE TITLE
[Space Exploration - cargo rocket custom fuel lib]  Crash on attempt to load save

### ISSUE THREAD

**Issue by matracy** [Quezler/glutenfree#19]
After updating from before the lobotomization, I get the following error when I go to load my existing save:
```
The mod Space Exploration - cargo rocket custom fuel lib (1.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event se-cargo-rocket-custom-fuel-lib::on_init()
__se-cargo-rocket-custom-fuel-lib__/control.lua:16: attempt to call global 'on_created_entity' (a nil value)
stack traceback:
	__se-cargo-rocket-custom-fuel-lib__/control.lua:16: in function <__se-cargo-rocket-custom-fuel-lib__/control.lua:6>
```

Creating new games works fine for freeplay and sandbox modes, as does loading the saves for fresh games.  On sandbox, it also did not matter if there was a rocket silo, or if the silo was fueled.  I did not test loading new freeplay saves with rocket silos.  I have attached the logfile, and am happy to provide further diagnostic info upon request.
[factorio-previous.log](https://github.com/user-attachments/files/16920302/factorio-previous.log)

**Comment by Quezler** [comment]
Whoops i only saw this just now, issue fixed, a complete oversight on my part.
