### ISSUE TITLE
[question] [upcycler] Guidance on how to create another upcycler machine with different ratios

### ISSUE THREAD

**Issue by heysokam** [Quezler/glutenfree#23]
Asking for some guidance. First timer modder here. It's my first day today.

After understanding item quality more, I think now I understand the purpose and reasoning of the upcycler mod, and it feels like an amazing solution for the gameplay that I was thinking of
The technology in this mod is still locked behind liquid, and I would love to have it available right from coal/burner age, but at a much much less powerful ratio of conversion so that the research is still worth aiming for (like now, but for a different reason)

So here is where the guidance request comes:
Reading the mod's source code I get a bit overwhelmed by all of the things I'm not quite understanding about what it is doing. It seems to be a relatively simple mod, so I'm aware it is absolutely a lack of skill/knowledge issue
Would it be possible to get some rough goal-posts / guidelines on what to look for exactly in the mod's codebase, considering my goal is to create (not replace) a separate upcycler machine _(lets call it burner upcycler)_ that is:
- 10% of the conversion power than the existing one
- Unlocked from the start

What part of the codebase I should be aiming my attention towards in order to achieve that goal?
Could there maybe be a simple way to do it without having to refactor a ton of code?

**Comment by Quezler** [comment]
Ah looks like we already had some contact over discord, let me know if you still have some questions.
