### ISSUE TITLE
Upcycler accumulates items when the next quality level is locked

### ISSUE THREAD

**Issue by rpdelaney** [Quezler/glutenfree#24]
When inserting a Cargo Bay into the Upcycler, the progress meter simply resets to 0% without any output.

**Comment by Quezler** [comment]
but does it _eventually_ output a quality cargo bay?

**Comment by rpdelaney** [comment]
I never saw it. How long do you want me to wait? :)

**Comment by Quezler** [comment]
can you send me the world?

**Comment by rpdelaney** [comment]
Sorry, I was dumb and I tore it down before making the bug report. If I can reproduce it I'll re-open the issue with a save file.

**Comment by rpdelaney** [comment]
Alright, I ran into this again. As it turns out, the final product is not being voided: rather, it's simply not being output, but rather accumulates in the machine.

![2024-12-30_17-45-12](https://github.com/user-attachments/assets/bf0ad64f-199e-4920-a895-def3b120a629)

If you deconstruct the upcycler on the far right, you will find many epic solar panels are left:

![2024-12-30_17-45-41](https://github.com/user-attachments/assets/88f0902e-09ab-4dd0-a3c3-8763855aa209)

[save file](https://0x0.st/8sGN.zip)

**Comment by Quezler** [comment]
did you unlock legendary quality? if there's no next quality unlocked the items just sit in there forever until you do. 😁

**Comment by rpdelaney** [comment]
No I haven't. As a user, I want the Upcycler to not accept inputs it can't process. Prioritize that according to your own judgment and interest :)

**Comment by Quezler** [comment]
understandable but the current mechanics of this mod don't really support it, and even if i did make it output it would be a needless waste of performance, a future mod of mine might deal with the issue in some other way
