### ISSUE TITLE
Deconstructed Upcycler left weird artifact

### ISSUE THREAD

**Issue by rpdelaney** [Quezler/glutenfree#25]
![2024-12-30_11-38-13](https://github.com/user-attachments/assets/eccbdf81-0045-444c-bf40-55d403dcacbf)
Not sure what this thing is or how to get rid of it.

It is possible that this is related to an interaction between Upcycler and [even-pickier-dollies](https://mods.factorio.com/mod/even-pickier-dollies), but I'm not certain.

[Save file](https://0x0.st/8s65.zip)

**Comment by Quezler** [comment]
it absolutely is, the item input is a separate entity (a linked chest), which does not get moved along with the main building

**Comment by rpdelaney** [comment]
Thank you very much for the fix! By any chance do you have suggestions for how I can get rid of these? 😓 
![2024-12-31_13-26-56](https://github.com/user-attachments/assets/5b6dc476-f09b-4849-9316-ce9c035430ad)

**Comment by Quezler** [comment]
since you've been so kind: try version 1.1.4, it should get rid of the leftover input slots, items inside will get voided tho.
